### ISSUE TITLE
uitleg custom proporties

### ISSUE THREAD

**Issue by yujing-student** [Nyathene/the-client-website#1]
in je root maak je dit aan in de css:
````
:root {
  --main-bg-color: cornflowerblue;
}
````

zet op een element of class een background en doe dit op meerdere elementen en kijk wat er dan gebeurt
````
.blank{
  background-color: var(--main-bg-color);
}
.starten{
  background-color: var(--main-bg-color);
}

````

hier staat de documentatie
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by Nyathene** [comment]
Bedankt! Ik heb dit toegepast bij [commit 6936158](https://github.com/Nyathene/the-client-website/commit/6936158d3c02f1379296e7eb92ec66c2a55d9a18)

**Comment by yujing-student** [comment]
je kan dit toepassen maar het hoeft niet

https://github.blog/news-insights/product-news/closing-issues-via-commit-messages/
